---
title: "About Me"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'aboutme.html'))})
date: "Last Updated: `r format(Sys.time(), '%B %e, %Y')`"
fontsize: 12pt
output: 
  html_document:
    includes:
      in_header: "favicon.html" 
---

***

## Coding Ability

```{r,  echo = FALSE, warning = FALSE}
library(data.table)
library(fmsb)
data = fread("coding.csv")

# Custom the radarChart !
radarchart( data  , axistype=1 , 
            
            #custom polygon
            pcol=rgb(0.2,0.5,0.5,0.9) , pfcol=rgb(0.2,0.5,0.5,0.5) , plwd=4 , 
            
            #custom the grid
            cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,120,25), cglwd=0.8,
            
            #custom labels
            vlcex=1.3 
)
```

## Hobbies

```{r,  echo = FALSE, warning = FALSE}
library(data.table)
library(fmsb)
data = fread("hobby.csv")

# Custom the radarChart !
radarchart( data  , axistype=1 , 
            
            #custom polygon
            pcol=rgb(0.4,0.5,0.5,0.9) , pfcol=rgb(0.4,0.5,0.5,0.5) , plwd=4 , 
            
            #custom the grid
            cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,120,25), cglwd=0.8,
            
            #custom labels
            vlcex=1.3 
)
```

## Subjects

```{r,  echo = FALSE, warning = FALSE}
library(data.table)
library(fmsb)
data = fread("subject.csv")

# Custom the radarChart !
radarchart( data  , axistype=1 , 
            
            #custom polygon
            pcol=rgb(0.9,0.5,0.5,0.9) , pfcol=rgb(0.9,0.5,0.5,0.5) , plwd=4 , 
            
            #custom the grid
            cglcol="grey", cglty=1, axislabcol="grey", caxislabels=seq(0,120,25), cglwd=0.8,
            
            #custom labels
            vlcex=1.3 
)
```




