---
title: "Conference Presentations"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'presentation.html'))})
date: "Last Updated: `r format(Sys.time(), '%B %e, %Y')`"
fontsize: 12pt
output: 
  html_document:
    includes:
      in_header: "favicon.html" 
---

During my Ph.D. career, I have presented my research work in several conferences on information systems, including INFORMS Annual Meeting, Symposium on Statistical Challenges in E-Commerce Research (SCECR), Conference on Information Systems and Technology (CIST), Workshop on Information Technologies and Systems (WITS), and China Summer Workshop on Information Management (CSWIM).

***

1) Hongfei Li, Jing Peng, Gang Wang, Xue Bai. [Impacts of Online Diaries on Sales of Credence Goods: Evidence from a Cosmetic Surgery Platform](https://www.abstractsonline.com/pp8/#!/4471/presentation/9999). INFORMS Annual Meeting (Session: Social Media Analytics I), Houston, Texas, October 22-25, 2017.

2) Hongfei Li, Ramesh Shankar, Jan Stallaert.[Invested or Indebted: Ex ante and Ex post Reciprocity in Online Knowledge Sharing Communities](http://2018.scecr.org/program/). SCECR 2018 (Session: Crowds), Rotterdam, Netherlands, June 18-19, 2018.

3) Hongfei Li, Jing Peng, Gang Wang, Xue Bai. [Online Diaries and Risky Products](http://cist2018.conferency.com/wp-content/uploads/2017/01/CIST-2018-Printable-Sheet1-2.pdf). CIST 2018 (Session: Healthcare), Phoenix, Arizona, November 3-4, 2018.

4) Hongfei Li, Jing Peng, Gang Wang, Xue Bai. [Online Diaries and Professional Service](http://2019.scecr.org/wp-content/uploads/2019/05/SCECR2019-Conference-Brochure.pdf). SCECR 2019, Hong Kong, China, June 11-12, 2019.

5) Hongfei Li, Jing Peng, Xinxin Li, Jan Stallaert. [The Impact of Ex post Risk-Reduction Mechanism on Online Sales: Evidence from Complications Insurance for Cosmetic Surgeries](http://2019.scecr.org/wp-content/uploads/2019/05/SCECR2019-Conference-Brochure.pdf). SCECR 2019, Hong Kong, China, June 11-12, 2019.

6) Xian Cao, Timothy Folta, Hongfei Li, Ruoqing Zhu. [A New Method to Understand the Online Word of Mouth Dynamics: Multi-View Sequential Canonical Covariance Analysis](http://2019.scecr.org/wp-content/uploads/2019/05/SCECR2019-Conference-Brochure.pdf). SCECR 2019, Hong Kong, China, June 11-12, 2019.

7) Hongfei Li, Ramesh Shankar, Jan Stallaert. [Disentangling the effect of Reciprocity on Online Knowledge Sharing Communities](http://2019.cswimworkshop.org/wp-content/uploads/2017/01/CSWIM-2019-Program_Final.pdf). CSWIM 2019, Shenzhen, China, June 29-30, 2019.

8) Fangda Han, Shun-Yang Lee, Hongfei Li, Jing Peng. [What Can Images Tell Us: A Prediction Study based on Facial Analysis](https://www.abstractsonline.com/pp8/#!/6818/presentation/4298). INFORMS Annual Meeting (Session: Artificial Intelligence and Machine Learning in Service), Seattle, Washington, October 20-23, 2019.

9) Hongfei Li, Jing Peng, Gang Wang, Xue Bai. [Disentangling the Effect of Longitudinal Consumer Reviews on Professional Service](https://www.abstractsonline.com/pp8/#!/6818/presentation/9694). INFORMS Annual Meeting (Session: Business Transformation in the Age of Analytics), Seattle, Washington, October 20-23, 2019.

10) Hongfei Li, Jing Peng, Xinxin Li, Jan Stallaert. When More is Less: The Effect of Add-on Insurance on the Consumption of Professional Services. WITS 2019, Munich, Germany, December 18-20, 2019.
