---
title: "Final Project"
knit: (function(input_file, encoding) {
  out_dir <- 'docs';
  rmarkdown::render(input_file,
 encoding=encoding,
 output_file=file.path(dirname(input_file), out_dir, 'project.html'))})
date: "Last Updated: `r format(Sys.time(), '%B %e, %Y')`"
fontsize: 12pt
output: 
  html_document:
    toc: true
    includes:
      in_header: "favicon.html" 
---

## Timeline
    
## Grading 

#### Group Choice 

Grading for the group choice is all-or-nothing based on summiting the google form before the deadline.

* Percent of final grade: 1%

#### Proposal

You will be graded on formatting, motivation, appropriateness of data, etc.

* Percent of final grade: 4%

#### Final Report 

* Percent of final grade: 25%

A breakdown of the points for the final report (with total points of 100). Please note that these are only suggestions and minimal requirements. The instructor and TAs reserve the right for interpreting the rubrics. 

* (5 points) Introduction and literature review:
    * Provide enough background to the reader such that they can understand your goal without seeing the data
* (20 points) Summary statistics and data visualization:
    * Is your summary statistics correct and informative
    * Is your visualization of the data correct and informative
* (20 points) Use of statistical learning methodology:
    * Have you used the appropriate methods for your dataset? 
    * Have you applied them correctly?
* (20 points) Interpretation of statistical learning methodology:
    * Do you arrive at the correct conclusions from the analyses you perform?
    * Do you correctly interpreting the analyses results in terms of the original scientific problem
* (5 points) Conclusion and discussion:
    * Objectively summarize your findings and analysis experience
* (10 points) Use of R:
    * Does your code perform the desired task?
    * Is your code readable?
* (10 points) Use of R markdown:
    * Are you properly utilizing R markdown to have a clean report?
    * Is irrelevant code/output hidden? 
    * Are plots, tables, etc. properly displayed
* (10 points) General Organization, Neatness, Readability:
    * Is your report easy to read with clear logic
    * Is it written in a manner such that a reader does not already need to be familiar with the data?
* __Bonus points__ (1 - 10)
    * This may be rewarded to project that analyzes an extremely complicated dataset.    
    
## FAQ

This section will likely be updated as we progress through the remainder of the semester.    
    
* __On the number of variables__: the requirement on the number of variables can be lowered if your data is rich enough. For example, a data that contains text may have a sentence/paragraph as one variable, however, the information in this variable is very rich. In that case, a single variable like this will satisfy the criteria.  

